### ISSUE TITLE
新的吸血客户端？

### ISSUE THREAD

**Issue by LazaruX512** [tonyhsie/qBittorrentBlockXunlei#1]
![anacrolix](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/121651381/c3a2d76e-1a74-4763-9b5b-cc807f87e399)
anacrolix最新力作？

**Comment by BeastSenpai1919810** [comment]
> 有它進行吸血行為的截圖嗎?

暂无，这种客户端到目前为止就见过一次，暂时也没有像是dt torrent这种，大规模出现、疑似pcdn的情况。
总之先放出来，如果有别人看到，希望他们能提供更多信息

**Comment by tonyhsie** [comment]
目前持續觀察，若它有實際吸血行為，再來處理

**Comment by LazaruX512** [comment]
![图片](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/121651381/4a3447e1-20b3-4915-a8bd-a8b91dac4b9a)
又一次看到了这个客户端

**Comment by tonyhsie** [comment]
如果沒有吸血行為的話，先關掉這個issue吧

以後有問題再另開issue處理就好了
