### ISSUE TITLE
Still won't ban this "weird" client

### ISSUE THREAD

**Issue by LazaruX512** [tonyhsie/qBittorrentBlockXunlei#10]
![image](https://github.com/user-attachments/assets/0e453fe4-f8ae-4b73-b485-b477225386bb)

**Comment by LazaruX512** [comment]
magnet:?xt=urn:btih:216a4a444bb761f46d5bef223abe136153abd28c
可以用奇蛋物语的种子复现

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/53d08537-96da-4c91-8c2b-4cfeb6c231e4)
另外，有些情况下程序真的会卡住

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/c9c0d0ae-9447-4545-b40d-270ce7740a9a)
我ban了几个"<u><<</u>"（上面那个特别泛滥的客户端）
重启客户端后，立马就卡住了

**Comment by tonyhsie** [comment]
> magnet:?xt=urn:btih:216a4a444bb761f46d5bef223abe136153abd28c 可以用奇蛋物语的种子复现

![圖片 2024-09-29 13-15-36](https://github.com/user-attachments/assets/966e413b-deb9-414e-bc3a-b1cf704c2215)

沒有復現，全都封殺了

**Comment by tonyhsie** [comment]
> ![image](https://private-user-images.githubusercontent.com/121651381/371824426-c9c0d0ae-9447-4545-b40d-270ce7740a9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODcxNzMsIm5iZiI6MTcyNzU4Njg3MywicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0NDI2LWM5YzBkMGFlLTk0NDctNDU0NS1iNDBkLTI3MGNlNzc0MGE5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTE0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmRjNzM2NDliY2IyMmViMGMxZWRiYjFmMGYyZGVlZDJkNWM5ZDI2MDU1NTkzZjMwZDNhY2VkNTNhMDBmOGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E46l3AflLtco1UBG2G2ba56wLcMaHi4znZf0OGb2jJ4) 我ban了几个"<<"（上面那个特别泛滥的客户端） 重启客户端后，立马就卡住了
> 
> 我猜一下：qBitBlock没办法处理一些unicode字符，然后程序就卡住了

當然不會有這種事

**Comment by tonyhsie** [comment]
> ![image](https://private-user-images.githubusercontent.com/121651381/371824237-d5df4126-35e8-4a0c-9c56-abf36f4e3484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODcxNzMsIm5iZiI6MTcyNzU4Njg3MywicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0MjM3LWQ1ZGY0MTI2LTM1ZTgtNGEwYy05YzU2LWFiZjM2ZjRlMzQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTE0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZlMTM2NmU4ZTdjYzVkYWRjNmFlYWJmNGRmZDFiNWI3ZGI4NDY5YmViOTE4MThkMGQzYjg3ZjIwYmY0YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CeekxrNFFdKC-n1CKjl20pylWzG5Y50BXHJ2RtXIt3Q) 另外，有些情况下程序真的会卡住（如图，13:05截的图，卡3mins了）

你試試提高 interval 看看是不是就不會卡了
或許是太頻繁對 qb web api 作操作導致的

**Comment by LazaruX512** [comment]
> > magnet:?xt=urn:btih:216a4a444bb761f46d5bef223abe136153abd28c 可以用奇蛋物语的种子复现
> 
> ![圖片 2024-09-29 13-15-36](https://private-user-images.githubusercontent.com/52758827/371824601-966e413b-deb9-414e-bc3a-b1cf704c2215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODc0MjIsIm5iZiI6MTcyNzU4NzEyMiwicGF0aCI6Ii81Mjc1ODgyNy8zNzE4MjQ2MDEtOTY2ZTQxM2ItZGViOS00MTRlLWJjM2EtYjFjZjcwNGMyMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYzZhZDE1ZThhMTQ1MjJmMzYyNjA5MTY0M2NiOGZhMjRlZDkzYTI1NWYwZTkyM2MzZjJmZjQ3ZDdjOTQ3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tlbBHny8lHWen9kFQ37TYfpNheLPRl1KQGD_G8zSazo)
> 
> 沒有復現，全都封殺了

你有没有看到`27.221.104.xxx`网段的IP啊？

**Comment by tonyhsie** [comment]
> > > magnet:?xt=urn:btih:216a4a444bb761f46d5bef223abe136153abd28c 可以用奇蛋物语的种子复现
> > 
> > 
> > ![圖片 2024-09-29 13-15-36](https://private-user-images.githubusercontent.com/52758827/371824601-966e413b-deb9-414e-bc3a-b1cf704c2215.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODc0MjIsIm5iZiI6MTcyNzU4NzEyMiwicGF0aCI6Ii81Mjc1ODgyNy8zNzE4MjQ2MDEtOTY2ZTQxM2ItZGViOS00MTRlLWJjM2EtYjFjZjcwNGMyMjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA1MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYzZhZDE1ZThhMTQ1MjJmMzYyNjA5MTY0M2NiOGZhMjRlZDkzYTI1NWYwZTkyM2MzZjJmZjQ3ZDdjOTQ3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tlbBHny8lHWen9kFQ37TYfpNheLPRl1KQGD_G8zSazo)
> > 沒有復現，全都封殺了
> 
> 你有没有看到`27.221.104.xxx`网段的IP啊？

只有被封殺的那兩批，剩下的客戶端都沒有 27. 開頭的 IP

**Comment by LazaruX512** [comment]
> > ![image](https://private-user-images.githubusercontent.com/121651381/371824237-d5df4126-35e8-4a0c-9c56-abf36f4e3484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODcxNzMsIm5iZiI6MTcyNzU4Njg3MywicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0MjM3LWQ1ZGY0MTI2LTM1ZTgtNGEwYy05YzU2LWFiZjM2ZjRlMzQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTE0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZlMTM2NmU4ZTdjYzVkYWRjNmFlYWJmNGRmZDFiNWI3ZGI4NDY5YmViOTE4MThkMGQzYjg3ZjIwYmY0YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CeekxrNFFdKC-n1CKjl20pylWzG5Y50BXHJ2RtXIt3Q) 另外，有些情况下程序真的会卡住（如图，13:05截的图，卡3mins了）
> 
> 你試試提高 interval 看看是不是就不會卡了 或許是太頻繁對 qb web api 作操作導致的

没用，改到5s了，还是卡住了

**Comment by tonyhsie** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/121651381/371824237-d5df4126-35e8-4a0c-9c56-abf36f4e3484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODcxNzMsIm5iZiI6MTcyNzU4Njg3MywicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0MjM3LWQ1ZGY0MTI2LTM1ZTgtNGEwYy05YzU2LWFiZjM2ZjRlMzQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTE0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZlMTM2NmU4ZTdjYzVkYWRjNmFlYWJmNGRmZDFiNWI3ZGI4NDY5YmViOTE4MThkMGQzYjg3ZjIwYmY0YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CeekxrNFFdKC-n1CKjl20pylWzG5Y50BXHJ2RtXIt3Q) 另外，有些情况下程序真的会卡住（如图，13:05截的图，卡3mins了）
> > 
> > 
> > 你試試提高 interval 看看是不是就不會卡了 或許是太頻繁對 qb web api 作操作導致的
> 
> 没用，改到5s了，还是卡住了

你卡住的時候，用瀏覽器能打開 http://localhost:13125/ 嗎？

**Comment by LazaruX512** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/121651381/371824237-d5df4126-35e8-4a0c-9c56-abf36f4e3484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1ODcxNzMsIm5iZiI6MTcyNzU4Njg3MywicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0MjM3LWQ1ZGY0MTI2LTM1ZTgtNGEwYy05YzU2LWFiZjM2ZjRlMzQ4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNTE0MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGZlMTM2NmU4ZTdjYzVkYWRjNmFlYWJmNGRmZDFiNWI3ZGI4NDY5YmViOTE4MThkMGQzYjg3ZjIwYmY0YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CeekxrNFFdKC-n1CKjl20pylWzG5Y50BXHJ2RtXIt3Q) 另外，有些情况下程序真的会卡住（如图，13:05截的图，卡3mins了）
> > > 
> > > 
> > > 你試試提高 interval 看看是不是就不會卡了 或許是太頻繁對 qb web api 作操作導致的
> > 
> > 
> > 没用，改到5s了，还是卡住了
> 
> 你卡住的時候，用瀏覽器能打開 http://localhost:13125/ 嗎？

WebUI嘛，能的

**Comment by LazaruX512** [comment]
我有点怀疑：我电脑上是不是缺什么运行库啊

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/75cd51da-ed6c-4f82-b6f2-1116c54051a4)
……一直卡

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/5cb89e06-37af-4528-95f0-5f59d41a8cb1)
还有个细节啊，这个程序一般不怎么吃性能的，但是一旦卡住，CPU占用就会变高

**Comment by LazaruX512** [comment]
我是不是应该用什么AIDA来分析下程序运行啊？
一直卡着也不是个事儿

**Comment by tonyhsie** [comment]
[qBittorrentBlockXunlei.v240929.test.zip](https://github.com/user-attachments/files/17177842/qBittorrentBlockXunlei.v240929.test.zip)

改了一版，你試試看會不會卡，或是卡住前印了什麼訊息

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/84454889-2d2e-455a-b17e-0ff8cdd1db03)
如图，这是新改版，它似乎在尝试ban某个客户端的时候卡住了

**Comment by LazaruX512** [comment]
之前Gopeed，xunlei都能ban，但是就没ban到过下面这个
![image](https://github.com/user-attachments/assets/2a8e9ed3-b3ff-42f6-b91e-6415d15232fc)

**Comment by LazaruX512** [comment]
<td title="ޭ__">ޭ__</td>
从网页端截取的客户端名

> 之前Gopeed，xunlei都能ban，但是就没ban到过下面这个 ![image](https://private-user-images.githubusercontent.com/121651381/371830626-2a8e9ed3-b3ff-42f6-b91e-6415d15232fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTEyNzUsIm5iZiI6MTcyNzU5MDk3NSwicGF0aCI6Ii8xMjE2NTEzODEvMzcxODMwNjI2LTJhOGU5ZWQzLWIzZmYtNDJmNi1iOTFlLTY0MTVkMTUyMzJmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNjIyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmJmNGUzOTlmNTk2YTEzYzMzYTllMjcwOWY4NzdhNmYxMjBjNDY2NjA4NTA3YTRiMGQ5Yzc5OWQwMDIzNmRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.D8zJyCJ_cV4PXoypEQnXSDJgNRYsRvBJi0tbM-nEnS8)

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/3f4c758b-6420-4c58-b8c6-c5a205759ef1)
非常奇怪的事情发生了：它在重复print这一行文字

**Comment by LazaruX512** [comment]
![image](https://github.com/user-attachments/assets/e5403dd1-3e83-4589-9ab5-da8a2f91aacb)
算了，我弃疗了

**Comment by tonyhsie** [comment]
你有其它電腦嗎？

用其它電腦來跑 qBittorrentBlockXunlei，IP 跟 Port 指定你這台電腦看看

**Comment by LazaruX512** [comment]
> 你有其它電腦嗎？
> 
> 用其它電腦來跑 qBittorrentBlockXunlei，IP 跟 Port 指定你這台電腦看看

没啊，不是垃圾佬（

**Comment by tonyhsie** [comment]
> ![image](https://private-user-images.githubusercontent.com/121651381/371824137-0e453fe4-f8ae-4b73-b485-b477225386bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgwODQ1MzEsIm5iZiI6MTcyODA4NDIzMSwicGF0aCI6Ii8xMjE2NTEzODEvMzcxODI0MTM3LTBlNDUzZmU0LWY4YWUtNGI3My1iNDg1LWI0NzcyMjUzODZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNFQyMzIzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjU0NjM5YmQzMWY3MDBjOGY5NWE3ZGFmMGIzOWI4ZTZlZjBjYjllZGVkZDRkYTJkZjUzY2UyMmE1MjgxYmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cXRWMOO5VQd24RD4_dxb8-pB99g2fCYjNZbgdKUzOaI)

v241005 會封鎖所有「名稱含有非 ASCII 可顯示字元(µ、μ 除外)」的客戶端
