### ISSUE TITLE
请求添加参数, 关闭功能 9.在程式啟動時，以及每隔 1 天會清空所有被擋的用戶 IP，避免永久封鎖可能會造成的誤鎖

### ISSUE THREAD

**Issue by ironstress** [tonyhsie/qBittorrentBlockXunlei#11]
有的客户端不是本项目认为的吸血用户, 
我有发现这样的用户: 下完种子就跑, 不进行做种, 
这样的用户我会手动封禁, 但是目前的程序会删除我的列表.

**Comment by tonyhsie** [comment]
如果有某些 IP 是你無論如何都要 ban 的
寫進 ipfilter.dat 讓 QB 自己處理，效率會比較好

你可以從[這個網頁](https://www.ipfilter.app/)右下角下載 ipfilter.dat
然後按照他的格式新增你要 ban 的 IP (它原本的內容，要不要清空都可以)
最後在 QB 裡設定好

![圖片 2024-10-17 21-33-15](https://github.com/user-attachments/assets/c422cbe6-fd1a-4d4f-a822-19e8537dee1b)

qBittorrentBlockXunlei 適合動態檢測跟處理即時的客戶端
ipfilter 適合靜態永久封鎖的客戶端
