### ISSUE TITLE
qbi客户端ip

### ISSUE THREAD

**Issue by pplokijuhyg** [tonyhsie/qBittorrentBlockXunlei#2]
可不可以客户端ip也设置为参数呢？比如我的qbi客户端在nas上，软件在windows虚拟机里面，这样的话，qbi的ip就不是127.0.0.1了

**Comment by tonyhsie** [comment]
OK，我找時間研究一下，下次改版增加對遠端 qB client 的支援

**Comment by tonyhsie** [comment]
最新版已添加對遠端 qBittorrent 的支援了
