### ISSUE TITLE
可否加入一个可选参数，从而判断用户是否希望上传给相对小众的客户端？

### ISSUE THREAD

**Issue by BeastSenpai1919810** [tonyhsie/qBittorrentBlockXunlei#3]
目前有许多人，出于便利性考虑，会使用诸如aria2、Xfplay、dandanplay、FDM这样的小众torrent客户端（我偶尔也会在手机上使用FDM）

请问，是否能加入一个可选的参数（比如说，`-niche (allow/refuse)`，对应的命令行则像是`qBittorrentBlockXunlei -i 30 -niche allow`）来识别使用者是否希望FDM这样的客户端连接至qBittorrent

我没有写过C#程序，电脑上的环境配置似乎也有问题（我此前只编译过c和rust程序，本地编译C#失败了），所以最后还是提交issue了……

总之，抱歉再次打扰您了

**Comment by tonyhsie** [comment]
要不要禁止特定客戶端，應該是基於該客戶端是否為正常的 bt 客戶端，而不是基於使用者數量的多寡

**Comment by BeastSenpai1919810** [comment]
> 要不要禁止特定客戶端，應該是基於該客戶端是否為正常的 bt 客戶端，而不是基於使用者數量的多寡

至少可以确认，aria2和FDM这类客户端是正常的、默认情况下有上传的客户端。在目前的规则中，默认将这两个客户端禁止确实是较为武断的做法

我没有用过dandanplay和Xfplay，无法确认这两者的情况，因此不做进一步评论

**Comment by tonyhsie** [comment]
封禁 aria2 跟 FDM 是根據另一個反吸血軟體的相同設置 https://github.com/ShenHongFei/utorrent-block-xunlei

在網路上搜尋一下，也有很多在詢問(或教學) aria2/FDM 要怎麼關掉上傳的文章
現在 BT 客戶端的選擇非常多，真正有分享精神的使用者，應該不會選擇 aria2/FDM 之類的陽春 BT client 吧？

**Comment by BeastSenpai1919810** [comment]
> 封禁 aria2 跟 FDM 是根據另一個反吸血軟體的相同設置 https://github.com/ShenHongFei/utorrent-block-xunlei
> 
> 在網路上搜尋一下，也有很多在詢問(或教學) aria2/FDM 要怎麼關掉上傳的文章 現在 BT 客戶端的選擇非常多，真正有分享精神的使用者，應該不會選擇 aria2/FDM 之類的陽春 BT client 吧？

手机端确实有许多人使用FDM图方便
支持多种下载链接的开源下载器中，FDM算是独一份的存在

**Comment by tonyhsie** [comment]
迅雷使用者其實也是圖方便而已

像 FDM 這類綜合下載器，其實根本不太強調 BT 的上傳功能，官網也只說可以下載 BT
實際的上載下載是如何運作，一般人也不得而知

另一套軟體封鎖 FDM 很多年了，也沒看到有人提出異議
我想這個封鎖還是有一定的合理性在的

**Comment by BeastSenpai1919810** [comment]
> 迅雷使用者其實也是圖方便而已
> 
> 像 FDM 這類綜合下載器，其實根本不太強調 BT 的上傳功能，官網也只說可以下載 BT 實際的上載下載是如何運作，一般人也不得而知
> 
> 另一套軟體封鎖 FDM 很多年了，也沒看到有人提出異議 我想這個封鎖還是有一定的合理性在的

![fdm_禁用上传](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/121651381/b33e8f5f-5290-4416-a2f2-e77806608209)
![qbit_禁用上传](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/121651381/6073771a-1a91-422a-a854-3aab53fe49b5)

技术无罪，下载器亦无罪

**Comment by tonyhsie** [comment]
多功能下載器跟純 BT 客戶端，並不能混為一談


目前封禁原則是，對方的進度為 0 或已上傳量是 0，才會進一步確認客戶端是不是在封禁名單內

如果 FDM 並不會假裝進度是 0，而且會確實上傳的話，並不會被封禁

**Comment by LaoshuBaby** [comment]
> 如果 FDM 並不會假裝進度是 0，而且會確實上傳的話

这点是有的，不管是FDM还是aria2还是uT，qBittorrent都有用过，如果您有FDM伪装进度骗别人上传的最好还是指明一下

（不过FDM不是开源的，恐怕难以自证清白了）

**Comment by LaoshuBaby** [comment]
> 現在 BT 客戶端的選擇非常多，真正有分享精神的使用者，應該不會選擇 aria2/FDM 之類的陽春 BT client 吧？

"陽春 BT client" 一词可能还需要您中译中一下，不过对 aria2 的批判确实不完全没有道理，因为它主要是用于http下载等场景，它的bt确实没有鼓励分享这一说（此外aria2用户另一类是极端自由软件爱好者，希望在纯命令行里做事，那只能说建议改用无头qb）

当然还是建议能加参数控制是否允许分享给这类客户端，给本项目使用者更多选择，毕竟这是个C#项目，需要编译的，而不是脚本语言的项目打开改一改就能生效

**Comment by LaoshuBaby** [comment]
> 封禁 aria2 跟 FDM 是根據另一個反吸血軟體的相同設置

此外既然您提到了反吸血，那也给出一些其他的反吸血（尤其是反迅雷系客户端）和不受欢迎行为客户端的配置：

* https://github.com/Simple-Tracker/qBittorrent-ClientBlocker/blob/master/config.json (没有ban掉FDM和aria2)
* https://github.com/Ghost-chu/PeerBanHelper/blob/master/README.md?plain=1#L37-L115 (有ban掉aria2，ban掉了FDM但是是基于peerID不标准作为理由)

这里不想讲一些所谓“客户端选择宗教化”之类的令人不舒服的言论，但是还是希望在ban客户端的时候谨慎考虑其影响

当然对于有明确不受欢迎行为的客户端那当然是要封掉的，但不是因为过于抽象的“BT/PT精神、共享精神”或潜在的“它很方便修改哎是不是有伪造风险”

顺便一提，您可能看到了一个“Taipei-Torrent dev”的client，倒不如把这类用来跑PCDN恶意下载拉平上传下载比例的客户端给ban掉

https://github.com/anacrolix/torrent/discussions/891#discussioncomment-8810897 这里有详细的分析

**Comment by tonyhsie** [comment]
> > 如果 FDM 並不會假裝進度是 0，而且會確實上傳的話
> 
> 这点是有的，不管是FDM还是aria2还是uT，qBittorrent都有用过，如果您有FDM伪装进度骗别人上传的最好还是指明一下
> 
> （不过FDM不是开源的，恐怕难以自证清白了）

我不知道 FDM 會不會這樣做，我的意思是，「只要它不會這麼做，那麼就不會被封禁了」

**Comment by tonyhsie** [comment]
> > 現在 BT 客戶端的選擇非常多，真正有分享精神的使用者，應該不會選擇 aria2/FDM 之類的陽春 BT client 吧？
> 
> "陽春 BT client" 一词可能还需要您中译中一下，不过对 aria2 的批判确实不完全没有道理，因为它主要是用于http下载等场景，它的bt确实没有鼓励分享这一说（此外aria2用户另一类是极端自由软件爱好者，希望在纯命令行里做事，那只能说建议改用无头qb）
> 
> 当然还是建议能加参数控制是否允许分享给这类客户端，给本项目使用者更多选择，毕竟这是个C#项目，需要编译的，而不是脚本语言的项目打开改一改就能生效

FDM 也一樣，並沒有鼓勵分享，因為本質上它們都是下載器

前面也提過了，只要 FDM 不會偽裝成進度 0 而且有在上傳的話，是不會被封禁的

**Comment by LaoshuBaby** [comment]
> 因為本質上它們都是下載器

也就是说您认为没有点明自己是“^.*((B|b)it|*)(T|t)orrent.*$”为卖点的客户端都只是下载器喽？那没得说了，大概这就是**客户端宗教**

**Comment by LaoshuBaby** [comment]
> 只要 FDM 不會偽裝成進度 0 而且有在上傳的話

有过此类报道吗？

**Comment by tonyhsie** [comment]
> > 因為本質上它們都是下載器
> 
> 也就是说您认为没有点明自己是“^._((B|b)it|_)(T|t)orrent.*$”为卖点的客户端都只是下载器喽？那没得说了，大概这就是**客户端宗教**

aria2 跟 FDM 是下載器，是客觀上的事實，但你的推論就純粹是主觀意識的扣帽子了


我前面說過，封禁 aria2 跟 FDM 是根據另一個反吸血軟體的相同設置 https://github.com/ShenHongFei/utorrent-block-xunlei

五年前該軟體就已經封禁 aria2 跟 FDM 了，我不覺得這五年來它們有改變過什麼


你有興趣的話，或許可以去問問對方為何要封禁 aria2 跟 FDM
