### ISSUE TITLE
新的吸血方式, 进度维持97.5%无变化

### ISSUE THREAD

**Issue by ironstress** [tonyhsie/qBittorrentBlockXunlei#6]
客户端: BitComet 1.92
行为: 种子大小为641.1MB, 上传量超过50MB, 进度维持97.5%无变化. 

前:
![屏幕截图 2024-06-01 171337](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/11043549/4580c6d2-bbca-4067-9fa8-7f682c839d57)
后:
![屏幕截图 2024-06-01 173432](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/11043549/37b7ba81-2ede-4260-b821-584c0799629a)

**Comment by tonyhsie** [comment]
收到

程式裡需要導入新的機制，才能阻擋這種客戶端
下一個版本會處理這個問題

**Comment by tonyhsie** [comment]
v240602 已能阻擋這種客戶端
