### ISSUE TITLE
New leecher client

### ISSUE THREAD

**Issue by LazaruX512** [tonyhsie/qBittorrentBlockXunlei#7]
![圖片](https://github.com/tonyhsie/qBittorrentBlockXunlei/assets/121651381/0d4fff77-1a37-4d2d-8a44-9339e288996f)
this "xm/torrent" is a new leecher client
新的吸血客户端"xm/torrent"

Btw, could you please add a new feature to read clients from a txt file? It'll make your maintenance easier.
另外，能劳烦加一个从txt文件中读取客户端的功能嘛？这会使你的维护更加容易

**Comment by tonyhsie** [comment]
v240706 版已封禁此類客戶端

另外，感謝你的提議

經過綜合評估後
目前暫時不考慮由外部檔案來對程式進行任何設定或操作
還是先維持 "使用者回報 -> 程式改版" 這樣的運作模式
