### ISSUE TITLE
疑似中国PCDN钓鱼的大批量临近IPv6地址

### ISSUE THREAD

**Issue by LazaruX512** [tonyhsie/qBittorrentBlockXunlei#8]
![圖片](https://github.com/user-attachments/assets/d5c8ae7f-4365-493f-8967-50e3b45f1708)
如图，这些qBittorrent客户端都来自一些临近的IPv6地址 (240e:660:150c:XXXX:1000::XX)
个人感觉它们又是中国反PCDN的钓鱼集群

**Comment by LazaruX512** [comment]
请问您有没有办法将这类大量来自于临近IP地址的拥护ban掉

**Comment by LazaruX512** [comment]
请问您有没有办法将这类大量来自于临近IP地址的用户ban掉

**Comment by tonyhsie** [comment]
> 请问您有没有办法将这类大量来自于临近IP地址的用户ban掉

同時有大量位址相近的 IP 連線的確很詭異
但如果要擋掉，需要有比較明確的規則

目前我還想到怎麼做比較好，如果有任何建議，歡迎提出來討論

**Comment by tonyhsie** [comment]
> 请问您有没有办法将这类大量来自于临近IP地址的用户ban掉

同時有大量位址相近的 IP 連線的確很詭異
目前已有初步的構想來防堵這類 IP，但需要進一步測試

請問您那邊有可容易復現這個問題的 torrent 檔或 magnet 連結嗎？

**Comment by LazaruX512** [comment]
> > 请问您有没有办法将这类大量来自于临近IP地址的用户ban掉
> 
> 同時有大量位址相近的 IP 連線的確很詭異 目前已有初步的構想來防堵這類 IP，但需要進一步測試
> 
> 請問您那邊有可容易復現這個問題的 torrent 檔或 magnet 連結嗎？

yts.mx上的TENET（2160p）

**Comment by tonyhsie** [comment]
> > > 请问您有没有办法将这类大量来自于临近IP地址的用户ban掉
> > 
> > 
> > 同時有大量位址相近的 IP 連線的確很詭異 目前已有初步的構想來防堵這類 IP，但需要進一步測試
> > 請問您那邊有可容易復現這個問題的 torrent 檔或 magnet 連結嗎？
> 
> yts.mx上的TENET（2160p）
![圖片 2024-08-20 12-40](https://github.com/user-attachments/assets/0bbdebc4-9336-46c5-897c-c50126ef2814)

看起來新機制能有效解決這個問題，晚點發布新版

**Comment by tonyhsie** [comment]
v240820 已解決此問題，麻煩您再 check 一下
